/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Principal.java
 *
 * Created on 12/11/2009, 09:42:08
 */

package Forms;

/**
 *
 * @author Administrator
 */
public class Principal2 extends javax.swing.JFrame {

    private Configuracion conf = new Configuracion();
    /** Creates new form Principal */
    public Principal2() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelEnvio = new javax.swing.JPanel();
        txtIpDestino = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtTextoAEnviar = new javax.swing.JTextArea();
        cmdEnviarTexto = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtArchivoAEnviar = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cmdEnviarArchivo = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        cmdConfiguracionLocal = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtTipoICMP = new javax.swing.JTextField();
        txtCodigoICMP = new javax.swing.JTextField();
        cmdEnviarPaqueteICMP = new javax.swing.JButton();
        panlConsolaEnvio = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtConsolaEnvio = new javax.swing.JTextArea();
        panelConsolaRecepcion = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtConsolaRecepcion = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Envio de informacion");

        panelEnvio.setBackground(new java.awt.Color(153, 153, 153));

        txtIpDestino.setText("192.168.159.212");

        jLabel1.setText("Direccion IP destino:");

        txtTextoAEnviar.setColumns(20);
        txtTextoAEnviar.setRows(5);
        jScrollPane1.setViewportView(txtTextoAEnviar);

        cmdEnviarTexto.setText("Enviar");
        cmdEnviarTexto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdEnviarTextoActionPerformed(evt);
            }
        });

        jLabel2.setText("Texto a enviar:");

        jLabel3.setText("Archivo a enviar:");

        cmdEnviarArchivo.setText("Enviar");
        cmdEnviarArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdEnviarArchivoActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Comic Sans MS", 3, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 0, 0));
        jLabel4.setText("Envio de informacion");

        cmdConfiguracionLocal.setText("Configuracion local");
        cmdConfiguracionLocal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdConfiguracionLocalActionPerformed(evt);
            }
        });

        jLabel7.setText("Codigo ICMP:");

        jLabel8.setText("Tipo ICMP:");

        txtTipoICMP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTipoICMPActionPerformed(evt);
            }
        });

        cmdEnviarPaqueteICMP.setText("Enviar");
        cmdEnviarPaqueteICMP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdEnviarPaqueteICMPActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelEnvioLayout = new javax.swing.GroupLayout(panelEnvio);
        panelEnvio.setLayout(panelEnvioLayout);
        panelEnvioLayout.setHorizontalGroup(
            panelEnvioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEnvioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelEnvioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelEnvioLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(344, 344, 344))
                    .addGroup(panelEnvioLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtIpDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cmdConfiguracionLocal)
                        .addContainerGap())
                    .addGroup(panelEnvioLayout.createSequentialGroup()
                        .addGroup(panelEnvioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel8))
                        .addGap(28, 28, 28)
                        .addGroup(panelEnvioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelEnvioLayout.createSequentialGroup()
                                .addComponent(txtTipoICMP, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCodigoICMP, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cmdEnviarPaqueteICMP))
                            .addGroup(panelEnvioLayout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 679, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cmdEnviarTexto)))
                        .addContainerGap())
                    .addGroup(panelEnvioLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(20, 20, 20)
                        .addComponent(txtArchivoAEnviar, javax.swing.GroupLayout.DEFAULT_SIZE, 679, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmdEnviarArchivo)
                        .addContainerGap())))
        );
        panelEnvioLayout.setVerticalGroup(
            panelEnvioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEnvioLayout.createSequentialGroup()
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(panelEnvioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtIpDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmdConfiguracionLocal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelEnvioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cmdEnviarTexto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2)
                    .addComponent(jScrollPane1, 0, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelEnvioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(txtCodigoICMP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmdEnviarPaqueteICMP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtTipoICMP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelEnvioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtArchivoAEnviar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(cmdEnviarArchivo))
                .addContainerGap())
        );

        panlConsolaEnvio.setBackground(new java.awt.Color(153, 153, 153));

        jLabel5.setFont(new java.awt.Font("Comic Sans MS", 3, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 0, 0));
        jLabel5.setText("Consola de envio");

        txtConsolaEnvio.setBackground(new java.awt.Color(204, 204, 204));
        txtConsolaEnvio.setColumns(20);
        txtConsolaEnvio.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        txtConsolaEnvio.setRows(5);
        txtConsolaEnvio.setEnabled(false);
        txtConsolaEnvio.setFocusable(false);
        jScrollPane2.setViewportView(txtConsolaEnvio);

        javax.swing.GroupLayout panlConsolaEnvioLayout = new javax.swing.GroupLayout(panlConsolaEnvio);
        panlConsolaEnvio.setLayout(panlConsolaEnvioLayout);
        panlConsolaEnvioLayout.setHorizontalGroup(
            panlConsolaEnvioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panlConsolaEnvioLayout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addComponent(jLabel5)
                .addContainerGap(184, Short.MAX_VALUE))
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 431, Short.MAX_VALUE)
        );
        panlConsolaEnvioLayout.setVerticalGroup(
            panlConsolaEnvioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panlConsolaEnvioLayout.createSequentialGroup()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE))
        );

        panelConsolaRecepcion.setBackground(new java.awt.Color(153, 153, 153));

        jLabel6.setFont(new java.awt.Font("Comic Sans MS", 3, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 0, 0));
        jLabel6.setText("Consola de recepcion");

        txtConsolaRecepcion.setBackground(new java.awt.Color(204, 204, 204));
        txtConsolaRecepcion.setColumns(20);
        txtConsolaRecepcion.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        txtConsolaRecepcion.setRows(5);
        txtConsolaRecepcion.setEnabled(false);
        txtConsolaRecepcion.setFocusable(false);
        jScrollPane3.setViewportView(txtConsolaRecepcion);

        javax.swing.GroupLayout panelConsolaRecepcionLayout = new javax.swing.GroupLayout(panelConsolaRecepcion);
        panelConsolaRecepcion.setLayout(panelConsolaRecepcionLayout);
        panelConsolaRecepcionLayout.setHorizontalGroup(
            panelConsolaRecepcionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelConsolaRecepcionLayout.createSequentialGroup()
                .addContainerGap(138, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(118, 118, 118))
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 435, Short.MAX_VALUE)
        );
        panelConsolaRecepcionLayout.setVerticalGroup(
            panelConsolaRecepcionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelConsolaRecepcionLayout.createSequentialGroup()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(panelEnvio, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panlConsolaEnvio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelConsolaRecepcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelEnvio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(panelConsolaRecepcion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panlConsolaEnvio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmdConfiguracionLocalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdConfiguracionLocalActionPerformed
        conf.setVisible(true);
    }//GEN-LAST:event_cmdConfiguracionLocalActionPerformed

    private void cmdEnviarTextoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdEnviarTextoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmdEnviarTextoActionPerformed

    private void cmdEnviarArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdEnviarArchivoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmdEnviarArchivoActionPerformed

    private void cmdEnviarPaqueteICMPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdEnviarPaqueteICMPActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_cmdEnviarPaqueteICMPActionPerformed

    private void txtTipoICMPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTipoICMPActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_txtTipoICMPActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdConfiguracionLocal;
    private javax.swing.JButton cmdEnviarArchivo;
    private javax.swing.JButton cmdEnviarPaqueteICMP;
    private javax.swing.JButton cmdEnviarTexto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JPanel panelConsolaRecepcion;
    private javax.swing.JPanel panelEnvio;
    private javax.swing.JPanel panlConsolaEnvio;
    private javax.swing.JTextField txtArchivoAEnviar;
    private javax.swing.JTextField txtCodigoICMP;
    private javax.swing.JTextArea txtConsolaEnvio;
    private javax.swing.JTextArea txtConsolaRecepcion;
    private javax.swing.JTextField txtIpDestino;
    private javax.swing.JTextArea txtTextoAEnviar;
    private javax.swing.JTextField txtTipoICMP;
    // End of variables declaration//GEN-END:variables

}
