/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Principal.java
 *
 * Created on 12/11/2009, 09:42:08
 */

package Forms;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;

import Exceptions.AddressException;
import NetworkProtocols.eventoN3;
import NetworkProtocols.IP.Datagram;
import NetworkProtocols.IP.DatagramPool;
import NetworkProtocols.IP.FragAssembler;
import NetworkProtocols.IP.Address.IpAddress;
import Utils.ApplicationInterface;
import Utils.BinaryManipulator;

/**
 *
 * @author Administrator
 */
public class Principal extends javax.swing.JFrame implements ApplicationInterface {
	private Configuracion conf = null;
	
	private static final long serialVersionUID = 1309657564278601339L;
	/** Creates new form Principal */
    public Principal(Configuracion c) {
        initComponents();
        this.conf = c;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelEnvio = new javax.swing.JPanel();
        cmdEnviarTexto = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtArchivoAEnviar = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cmdEnviarArchivo = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        cmdEnviarPaqueteICMP = new javax.swing.JButton();
        txtTextoAEnviar = new javax.swing.JTextField();
        txtTipoICMP = new javax.swing.JComboBox();
        txtCodigoICMP = new javax.swing.JComboBox();
        panlConsolaEnvio = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtConsolaEnvio = new javax.swing.JTextArea();
        panelConsolaRecepcion = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtConsolaRecepcion = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Envio de informacion");

        panelEnvio.setBackground(new java.awt.Color(153, 153, 153));

        cmdEnviarTexto.setText("Enviar");
        cmdEnviarTexto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdEnviarTextoActionPerformed(evt);
            }
        });

        jLabel2.setText("Texto a enviar:");

        jLabel3.setText("Archivo a enviar:");

        cmdEnviarArchivo.setText("Enviar");
        cmdEnviarArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdEnviarArchivoActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Comic Sans MS", 3, 18));
        jLabel4.setForeground(new java.awt.Color(102, 0, 0));
        jLabel4.setText("Envio de informacion");

        jLabel7.setText("Codigo ICMP:");

        jLabel8.setText("Tipo ICMP:");

        cmdEnviarPaqueteICMP.setText("Enviar");
        cmdEnviarPaqueteICMP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdEnviarPaqueteICMPActionPerformed(evt);
            }
        });

        txtTipoICMP.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "3", "4", "5", "8", "11", "12", "13", "15" })); 
        txtTipoICMP.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtTipoICMPFocusLost(evt);
            }
        });
        txtCodigoICMP.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" })); 

        javax.swing.GroupLayout panelEnvioLayout = new javax.swing.GroupLayout(panelEnvio);
        panelEnvio.setLayout(panelEnvioLayout);
        panelEnvioLayout.setHorizontalGroup(
            panelEnvioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEnvioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelEnvioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelEnvioLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(344, 344, 344))
                    .addGroup(panelEnvioLayout.createSequentialGroup()
                        .addGroup(panelEnvioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel8)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelEnvioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtArchivoAEnviar, javax.swing.GroupLayout.DEFAULT_SIZE, 695, Short.MAX_VALUE)
                            .addGroup(panelEnvioLayout.createSequentialGroup()
                                .addComponent(txtTipoICMP, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCodigoICMP, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cmdEnviarPaqueteICMP))
                            .addComponent(txtTextoAEnviar, javax.swing.GroupLayout.DEFAULT_SIZE, 695, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelEnvioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cmdEnviarArchivo)
                            .addComponent(cmdEnviarTexto))
                        .addContainerGap())))
        );
        panelEnvioLayout.setVerticalGroup(
            panelEnvioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEnvioLayout.createSequentialGroup()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelEnvioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelEnvioLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(15, 15, 15)
                        .addGroup(panelEnvioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txtTipoICMP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelEnvioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(cmdEnviarArchivo)))
                    .addGroup(panelEnvioLayout.createSequentialGroup()
                        .addGroup(panelEnvioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTextoAEnviar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmdEnviarTexto))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelEnvioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtCodigoICMP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmdEnviarPaqueteICMP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtArchivoAEnviar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        panlConsolaEnvio.setBackground(new java.awt.Color(153, 153, 153));

        jLabel5.setFont(new java.awt.Font("Comic Sans MS", 3, 18));
        jLabel5.setForeground(new java.awt.Color(102, 0, 0));
        jLabel5.setText("Consola de envio");

        txtConsolaEnvio.setBackground(new java.awt.Color(204, 204, 204));
        txtConsolaEnvio.setColumns(20);
        txtConsolaEnvio.setFont(new java.awt.Font("Monospaced", 0, 12));
        txtConsolaEnvio.setRows(5);
        txtConsolaEnvio.setEnabled(false);
        txtConsolaEnvio.setFocusable(false);
        jScrollPane2.setViewportView(txtConsolaEnvio);

        javax.swing.GroupLayout panlConsolaEnvioLayout = new javax.swing.GroupLayout(panlConsolaEnvio);
        panlConsolaEnvio.setLayout(panlConsolaEnvioLayout);
        panlConsolaEnvioLayout.setHorizontalGroup(
            panlConsolaEnvioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panlConsolaEnvioLayout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addComponent(jLabel5)
                .addContainerGap(184, Short.MAX_VALUE))
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 431, Short.MAX_VALUE)
        );
        panlConsolaEnvioLayout.setVerticalGroup(
            panlConsolaEnvioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panlConsolaEnvioLayout.createSequentialGroup()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 245, Short.MAX_VALUE))
        );

        panelConsolaRecepcion.setBackground(new java.awt.Color(153, 153, 153));

        jLabel6.setFont(new java.awt.Font("Comic Sans MS", 3, 18));
        jLabel6.setForeground(new java.awt.Color(102, 0, 0));
        jLabel6.setText("Consola de recepcion");

        txtConsolaRecepcion.setBackground(new java.awt.Color(204, 204, 204));
        txtConsolaRecepcion.setColumns(20);
        txtConsolaRecepcion.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        txtConsolaRecepcion.setRows(5);
        txtConsolaRecepcion.setEnabled(false);
        txtConsolaRecepcion.setFocusable(false);
        jScrollPane3.setViewportView(txtConsolaRecepcion);

        javax.swing.GroupLayout panelConsolaRecepcionLayout = new javax.swing.GroupLayout(panelConsolaRecepcion);
        panelConsolaRecepcion.setLayout(panelConsolaRecepcionLayout);
        panelConsolaRecepcionLayout.setHorizontalGroup(
            panelConsolaRecepcionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelConsolaRecepcionLayout.createSequentialGroup()
                .addContainerGap(138, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(118, 118, 118))
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 435, Short.MAX_VALUE)
        );
        panelConsolaRecepcionLayout.setVerticalGroup(
            panelConsolaRecepcionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelConsolaRecepcionLayout.createSequentialGroup()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 245, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(panelEnvio, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panlConsolaEnvio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelConsolaRecepcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelEnvio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(panelConsolaRecepcion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panlConsolaEnvio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmdEnviarTextoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdEnviarTextoActionPerformed
		byte[] message1 = this.txtTextoAEnviar.getText().getBytes();
		Datagram d1 = new Datagram(message1.length);
		d1.setDestAddress(conf.getAddrDstSimulada()); //La direccion origen del datagram original es la destino de este
		d1.setsourceAddress(conf.getIP().getLocalIpAddress());
		d1.setProtocol(6); //TCP, tomado en este caso como aplicacion
		d1.setData(message1, true);
		d1.genChecksum();
		eventoN3 evReq = new eventoN3(eventoN3.SEND, d1);
		conf.getIP().addLoc(evReq);
    }//GEN-LAST:event_cmdEnviarTextoActionPerformed

    private void cmdEnviarArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdEnviarArchivoActionPerformed
		byte[] message1 = BinaryManipulator.readByteArray(this.txtArchivoAEnviar.getText());
		Datagram d1 = new Datagram(message1.length);
		d1.setDestAddress(conf.getAddrDstSimulada()); //La direccion origen del datagram original es la destino de este
		d1.setsourceAddress(conf.getIP().getLocalIpAddress());
		d1.setProtocol(6); //TCP, tomado en este caso como aplicacion
		d1.setData(message1, true);
		d1.genChecksum();
		eventoN3 evReq = new eventoN3(eventoN3.SEND, d1);
		conf.getIP().addLoc(evReq);
    }//GEN-LAST:event_cmdEnviarArchivoActionPerformed

    private void cmdEnviarPaqueteICMPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdEnviarPaqueteICMPActionPerformed
    	if (Integer.parseInt(this.txtTipoICMP.getSelectedItem().toString()) != 12)
    		conf.getIP().getICMPProtocol().send(new Integer(Integer.parseInt(this.txtTipoICMP.getSelectedItem().toString())).byteValue(), new Integer(Integer.parseInt(this.txtCodigoICMP.getSelectedItem().toString())).byteValue(), conf.getAddrDstSimulada(), new Datagram(36));
    	else{
    		Datagram data = new Datagram(36);
    		data.setsourceAddress(conf.getAddrDstSimulada());
    		conf.getIP().getICMPProtocol().send(new Integer(Integer.parseInt(this.txtTipoICMP.getSelectedItem().toString())).byteValue(), new Integer(Integer.parseInt(this.txtCodigoICMP.getSelectedItem().toString())).byteValue(), (byte)0x03, data);
    	}
    }//GEN-LAST:event_cmdEnviarPaqueteICMPActionPerformed

    private void txtTipoICMPFocusLost(java.awt.event.FocusEvent evt) {
    	// "3", "4", "5", "8", "11", "12", "13", "15"
    	switch (Integer.parseInt(this.txtTipoICMP.getSelectedItem().toString())){
			case 3:
		    	txtCodigoICMP.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0", "1", "2", "3", "4", "5" }));
		    	break;
			case 4:
		    	txtCodigoICMP.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0" }));
		    	break;
			case 5:
		    	txtCodigoICMP.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0", "1", "2", "3" }));
		    	break;
			case 8:
		    	txtCodigoICMP.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0" }));
		    	break;
			case 11:
		    	txtCodigoICMP.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0", "1" }));
		    	break;
			case 12:
		    	txtCodigoICMP.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0" }));
		    	break;
			case 13:
		    	txtCodigoICMP.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0" }));
		    	break;
			case 15:
		    	txtCodigoICMP.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0" }));
		    	break;
    	}
    }

	@Override
	public void receiveMessage(Object o) {
		byte receive[] = (byte[])o;
		System.out.println("Datos recibidos: " + toByteValueString(receive));
	}
    
	public String toByteValueString(byte[] val){
		String ret = new String();
		for (int i = 0; i < val.length; i++)
			ret = ret.concat(String.format("%X", val[i]).toUpperCase());
		return ret;
	}

    
    
    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdEnviarArchivo;
    private javax.swing.JButton cmdEnviarPaqueteICMP;
    private javax.swing.JButton cmdEnviarTexto;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JPanel panelConsolaRecepcion;
    private javax.swing.JPanel panelEnvio;
    private javax.swing.JPanel panlConsolaEnvio;
    private javax.swing.JTextField txtArchivoAEnviar;
    private javax.swing.JComboBox txtCodigoICMP;
    private javax.swing.JTextArea txtConsolaEnvio;
    private javax.swing.JTextArea txtConsolaRecepcion;
    private javax.swing.JTextField txtTextoAEnviar;
    private javax.swing.JComboBox txtTipoICMP;
    // End of variables declaration//GEN-END:variables

}
